### ISSUE TITLE
Add Spartan to the themes page

### ISSUE THREAD

**Issue by thomasdavis** [francescoes/jsonresume-theme-spartan#1]
Thanks Francesco! http://jsonresume.org/themes/

**Comment by phoinixi** [comment]
That's great. Thank you! People likes more this, check it out https://github.com/francescoes/jsonresume-theme-stackoverflow

**Comment by thomasdavis** [comment]
Added!

I should have done this  a long time ago =D

In the future, if I am slow again, just pull request this file -> https://github.com/jsonresume/resume-website/blob/gh-pages/_data/themes.yaml
